name: Build and release
on:
  push:
    branches:
      - '**'
       
env:
  native_image_opts: --verbose --enable-http --enable-https -H:ReflectionConfigurationFiles=build/classes/java/main/META-INF/graal/reflect.json
#  native_image_opts: --verbose --initialize-at-build-time=org.apache.logging.slf4j.Log4jLogger,org.apache.logging.log4j.spi.AbstractLogger,org.apache.logging.log4j.core.Logger,org.apache.logging.log4j.Level,org.apache.logging.slf4j.Log4jLoggerFactory
          
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/fcli.jar

  release_nix:
    name: native-image-nix
    #if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.2.0.java11'

      - name: Install GraalVM's native-image extension
        run: gu install native-image

      - uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Create native fcli
        run: mkdir -p native-image/${{ matrix.os }} && native-image ${{ env.native_image_opts }} -jar ./artifact/fcli.jar native-image/${{ matrix.os }}/fcli
        
      - name: Basic test of native fcli
        run: ./native-image/${{ matrix.os }}/fcli --help && ./native-image/${{ matrix.os }}/fcli fod --help

      - uses: actions/upload-artifact@v2
        with:
          path: ./native-image

  release_win:
    name: native-image-win
    #if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-2019
    steps:
    - uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '21.2.0.java11'

    - name: Install GraalVM's native-image extension
      run: ${{ env.JAVA_HOME }}\bin\gu.cmd install native-image

    - uses: actions/download-artifact@v2
      with:
        path: ./

    - name: Create native fcli
      run: >-
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&
        mkdir native-image\win &&
        ${{ env.JAVA_HOME }}\bin\native-image.cmd ${{ env.native_image_opts }} -jar .\artifact\fcli.jar native-image\win\fcli
      shell: cmd
      
    - name: Basic test of native fcli
      run: |
        .\native-image\win\fcli.exe --help 
        .\native-image\win\fcli.exe fod --help

    - uses: actions/upload-artifact@v2
      with:
        path: ./native-image